from dotenv import load_dotenv
from langchain.chat_models import init_chat_model
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, HumanMessagePromptTemplate, SystemMessagePromptTemplate
from langchain_core.runnables import RunnablePassthrough

load_dotenv()

llm = init_chat_model("gemini-2.0-flash-001", model_provider="google_genai")

# --- Define the first prompt: Outline Generator ---
outline_prompt = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template("You are a helpful assistant that creates blog post outlines."),
    HumanMessagePromptTemplate.from_template("Create a concise outline for a blog post about the topic: {topic}"),
])

# --- Define the second prompt: Blog Post Writer ---
# This prompt needs both the original topic AND the outline generated by the first step
blog_post_prompt = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template("You are a helpful assistant that writes blog posts based on the given topic and an outline."),
    HumanMessagePromptTemplate.from_template("Write a blog post about the topic: {topic}\n\nUse the following outline:\n{outline}"),
])

outline_template_values = {
    "topic": "Panda - the animal",
}

outline_llm = outline_prompt | llm | StrOutputParser()

outline = outline_llm.invoke(outline_template_values)

blog_post_template_values = {
    "topic": "Panda - the animal",
    "outline": outline,
}

## outlines the issue without chaining

blog_post_llm = blog_post_prompt | llm | StrOutputParser()

full_blog_post = blog_post_llm.invoke(blog_post_template_values)

# print(full_blog_post)

# now how this is solved with chaining

chain_full_post = RunnablePassthrough.assign(
    outline=outline_llm # Run outline chain and assign result to 'outline' key
) | blog_post_llm


full_blog_post = chain_full_post.invoke(outline_template_values)

print(full_blog_post)


